######################################################################
# Automatically generated by qmake (3.0) Fri Jan 13 10:08:33 2017
######################################################################

TEMPLATE = lib
TARGET = ModbusStructs
INCLUDEPATH = /home/fresep/Programs/arduino-1.8.0/hardware/teensy/avr/cores/teensy3 \
	/home/fresep/Arduino/libraries/ModbusStructs

# Input
HEADERS += ModbusStack.h

SOURCES += ModbusStack.cpp

DISTFILES += \
    keywords.txt


