######################################################################
# Automatically generated by qmake (3.0) Fri Jan 13 10:08:33 2017
######################################################################

TEMPLATE = lib
TARGET = ModbusStructs
INCLUDEPATH = /home/fresep/Programs/arduino-1.8.0/hardware/teensy/avr/cores/teensy3

# Input
HEADERS += ModbusStructs.h

SOURCES += ModbusStructs.cpp

DISTFILES += \
    keywords.txt


